---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stateful-api-service
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stateful-api-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    name: stateful-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-api
spec:
  replicas: 5
  selector:
    matchLabels:
      name: stateful-api
  template:
    spec:
      containers:
        - name: api
          image: piotrostr/stateful-api
          ports:
            - containerPort: 8080
status: {}
