---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: stateful-api-service
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stateful-api-service
  labels:
    name: stateful-api-service
spec:
  type: NodePort
  ports:
    - port: 8080
  selector:
    app: stateful-api
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: data-dir
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-api-deployment
spec:
  serviceName: stateful-api-service
  replicas: 3
  selector:
    matchLabels:
      app: stateful-api
  template:
    metadata:
      labels:
        app: stateful-api
    spec:
      containers:
        - name: api
          image: piotrostr/stateful-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 150m
            limits:
              memory: 128Mi
          volumeMounts:
            - mountPath: /data
              name: data-dir
  volumeClaimTemplates:
    - metadata:
        name: data-dir
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: data-dir
        resources:
          requests:
            storage: 1Gi
