apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gke-stateful
build:
  artifacts:
  - image: piotrostr/stateful-api
    context: api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifest.yaml
